// From Codecademy

// Define a var userName set to emptystring
let userName = "Bobo";

// Create ternary expression that decides what to do if the user enters a name or not
userName ? console.log(`Hello, ${userName}!`) : console.log("Hello!");

// Create a var named UserQuestion - the value of the var should be a string that is the question the user wants to ask the Magic 8 Ball
const userQuestion = "Will I become a millionare?";

// Log the question
console.log(`${userName} asks, "${userQuestion}"`);

// Generate a random number between 0 and 7 - Math.random() returns 0 or 1, hence * 8 to generate 0 to 8. Use Math.floor to ensure a whole number to round down
const randomNumber = Math.floor(Math.random() * 8);

// Create eightBall var and set it to an empty string - this will return a string depending on the value generated by the randomNumber
let eightBall = "";

// control flow that takes in the randomNumber and then assigns eightBall to a reply that a Magic Eight ball would return

switch (randomNumber) {
  case 0:
    eightBall = "It is certain";
    break;
  case 1:
    eightBall = "It is decidedly so";
    break;
  case 2:
    eightBall = "Reply hazy try again";
    break;
  case 3:
    eightBall = "Cannot predict now";
    break;
  case 4:
    eightBall = "Do not count on it";
    break;
  case 5:
    eightBall = "My sources say no";
    break;
  case 6:
    eightBall = "Outlook not so good";
    break;
  default:
    eightBall = "Signs point to yes";
    break;
}

// log the Magic Eight Ball's answer, the value of the eightBall variable
console.log(`The Magic Eight Ball answered: ${eightBall}`);
